name: Status Check for Main Branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Echo something
        run: echo "This is a dummy status check"

      - name: Named Status Check
        uses: actions/github-script@v7
        with:
          script: |
            core.notice(' GitHub now recognizes this as a status check!')
